apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk-stack
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
        ssl => false
      }
    }
    
    filter {
      if [fields][log_type] == "elk-stack" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
        }
        
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        
        mutate {
          add_field => { "source_type" => "elk-stack" }
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["https://elasticsearch:9200"]
        index => "elk-logs-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "elastic123"
        ssl => true
        ssl_certificate_verification => false
        cacert => "/usr/share/logstash/config/certs/ca.pem"
      }
      
      stdout { 
        codec => rubydebug 
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          cp -r /certs-input/* /certs-output/
          chown -R 1000:1000 /certs-output
          chmod -R 644 /certs-output/*.pem
          chmod -R 600 /certs-output/*-key.pem
        volumeMounts:
        - name: ssl-certs-input
          mountPath: /certs-input
        - name: ssl-certs-output
          mountPath: /certs-output
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.17.9
        ports:
        - containerPort: 5044
          name: beats
        - containerPort: 9600
          name: http
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms1g -Xmx2g"
        - name: PIPELINE_WORKERS
          value: "2"
        - name: LOG_LEVEL
          value: "info"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        - name: ssl-certs-output
          mountPath: /usr/share/logstash/config/certs
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
      - name: ssl-certs-input
        secret:
          secretName: elk-ssl-certs
      - name: ssl-certs-output
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk-stack
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
  - name: http
    port: 9600
    targetPort: 9600
  type: ClusterIP