apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk-stack
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      if [fields][log_type] == "elk-stack" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
        }
        
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        
        mutate {
          add_field => { "source_type" => "elk-stack" }
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["https://10.106.80.20:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "elastic123"
        ssl => true
        ssl_certificate_verification => false
      }
      
      stdout { 
        codec => rubydebug 
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      nodeSelector:
        kubernetes.io/hostname: "worker-1"
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.17.9
        ports:
        - containerPort: 5044
          name: beats
        - containerPort: 9600
          name: http
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms1g -Xmx2g"
        - name: PIPELINE_WORKERS
          value: "2"
        - name: LOG_LEVEL
          value: "info"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        - name: ssl-certs
          mountPath: /usr/share/logstash/certs
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
      - name: ssl-certs
        secret:
          secretName: elk-ssl-certs
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk-stack
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
  - name: http
    port: 9600
    targetPort: 9600
  type: ClusterIP